# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    docker pull owasp/zap2docker-stable
    mkdir -p report
    chmod 777 report
    docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://demo.testfire.net -r baseline-report.html -s '/src' -o '/report' --format "HTML"

  displayName: 'owasp zap'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(System.DefaultWorkingDirectory)/report
    ArtifactName: 'Report'
    publishLocation: 'Container'