# trigger:
#  - master

pool:
  vmImage: ubuntu-latest
variables:
- group: New_variable_group_27-Dec

steps: 

- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    semgrep login
    semgrep ci
  env: 
    SEMGREP_PR_ID: $(System.PullRequest.PullRequestNumber)
