trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
- group: Semgrep app token group

steps:
- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    semgrep ci
  env:
    SEMGREP_PR_ID: $(System.PullRequest.PullRequestNumber)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/'
    artifactType: 'pipeline'
    artifactName: 'scan-results'
