# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    docker pull owasp/zap2docker-stable
    docker run -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py -r report.html -t http://demo.testfire.net
  displayName: 'Run a multi-line script'
