# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    docker pull owasp/zap2docker-stable
    docker run -v $(pwd):/zap/wrk/:rw --user root -t owasp/zap2docker-stable zap-full-scan.py -t https://example.com/ -r full-scan-report.html

  displayName: 'owasp zap'

- task: PublishBuildArtifacts@1

  inputs:

    PathtoPublish: $(System.DefaultWorkingDirectory)/report/full-scan-report.html

    ArtifactName: 'Report'

    publishLocation: 'Container'