# This is a basic workflow that is manually triggered

name: Manual workflow


on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
jobs:
  snyk-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0
      with:
    # Repository name with owner. For example, actions/checkout
        repository: ${{ github.WebGoat }}

    - name: Snyk
      uses: snyk/actions@0.3.0
      with:
        command: auth 0655ea4d-2e55-4697-b726-9c832e36004a
    - name: Snyk test
      uses: snyk/actions@0.3.0
      with:
        command: code test $(pwd)
