# This is a basic workflow that is manually triggered

name: Manual workflow


on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
jobs:
  snyk-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.6.0
      with:
    # Repository name with owner. For example, actions/checkout
        repository: ${{ github.WebGoat }}

    - name: Snyk
      uses: snyk/actions@0.3.0
      with:
        command: auth 973ff940-4eb2-4c72-8a46-00fa3a962a69
    - name: Snyk test
      uses: snyk/actions@0.3.0
      with:
        command: code test $(pwd)
